# Generated by Django 4.2.16 on 2024-11-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
    ]
